#!/bin/bash


module load python/anaconda/3.6.4
module load hmmer/3.1b2
module load repeatmasker/4.0.6
module load cdhit/4.7
module load ncbi-blast/2.2.31+


awk '{if ($1~/[0-9]+/) print $10"\t"$1}' genome.final.fa.pass.list >  genome.final.fa.pass.list.extract

perl /home/olo0002/LTR_retriever_v.7/LTR_retriever/bin/call_seq_by_list.pl genome.final.fa.pass.list.extract -C genome.final.fa > genome_pass_list.fa 

