#!/bin/bash
#harvest and digest script

module load genometools/1.5.10

gt suffixerator -db genome.final.fa -indexname genome.final.fa -tis -suf -lcp -des -ssp -sds -dna
gt ltrharvest -index genome.final.fa -seqids yes -minlenltr 100 -maxlenltr 7000 -mintsd 4 -maxtsd 6 -similar 85 -vic 10 -seed 20 -motif TGCA -motifmis 1 > Lamel.harvest.scn
gt ltrharvest -index genome.final.fa -seqids yes -minlenltr 100 -maxlenltr 7000 -mintsd 4 -maxtsd 6 -similar 85 -vic 10 -seed 20 > Lamel.harvest.nonTGCA.scn

module load ltrfinder/1.07

ltr_finder -D 15000 -d 1000 -l 100 -L 7000 -p 20 -C -M 0.85 genome.final.fa > Lamel.finder.scn
